### Production environment settings

# STS role and target account
Sts.Role: arn:aws:iam::398099758646:role/Admin

# Network settings
Stack.Inputs.VpcName: Default

# Application settings
Stack.Inputs.ApplicationDesiredCount: 1
Stack.Inputs.ApplicationImageId: ami-098251b61b80a478a
Stack.Inputs.ApplicationInstanceType: t2.micro
Stack.Inputs.KeyName: admin

# Proxy settings
Stack.Inputs.ProxyImage: 398099758646.dkr.ecr.ap-northeast-1.amazonaws.com/dockerproductionaws/squid
Stack.Inputs.ProxyWhitelist: .nicolasmartin58.org
